services:
  web:
    container_name: levinswap-stake
    build: .
    networks:
      - traefik-realt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.levinswap-stake.rule=Host(`stake.levinswap.realtoken.community`)"
      - "traefik.http.routers.levinswap-stake.entrypoints=websecure"
      - "traefik.http.services.levinswap-stake.loadbalancer.server.port=3000"
    restart: always

networks:
  traefik-realt:
    external: true
